model_name: "bert-base-cased"
subtoken_pooling: "first"
fine_tune: True
hidden_size: 768
seed: 42

dataset_path: "/Users/tompham/Documents/CS6320_Project/Filtered-Semi-Markov-CRF/CoNLL 2003"

max_width: 15
span_mode: "endpoints"

dropout: 0.4
sample_rate: 0.6
model_type: "fsemicrf"
decoding: "global"

soft_filter: False

learning_rates:
  - 1e-5
  - 1e-4

weight_decay:
  - 1e-3
  - 1e-2

batch_size:
  - 16
  - 32

training:
  - epoch: 10
    steps: 10000
    warmup_ratio: 0.001
    eval_steps: 250

root_dir: "logs"
